"""add reset_token to base user models

Revision ID: 5d7ac9107a0c
Revises: a74e0e1dcb28
Create Date: 2026-03-14 14:03:11.544501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7ac9107a0c'
down_revision = 'a74e0e1dcb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_owner_reset_token'), ['reset_token'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_reset_token'), ['reset_token'])

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_worker_reset_token'), ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_worker_reset_token'), type_='unique')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_reset_token'), type_='unique')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_owner_reset_token'), type_='unique')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
