"""initial migration

Revision ID: ee1d55eaec16
Revises: 
Create Date: 2026-03-14 13:21:10.180978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1d55eaec16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_complaint')
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_owner_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_owner_google_id'), ['google_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_owner_phone'), ['phone'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_review_booking_id'), ['booking_id'])

    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excellence_categories', sa.Text(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('super_admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_super_admin_username'), ['username'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_google_id'), ['google_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_phone'), ['phone'])

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('salon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_worker_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_worker_google_id'), ['google_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_worker_phone'), ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_worker_phone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_worker_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_worker_email'), type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('salon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('google_id')
        batch_op.drop_column('email')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_phone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('google_id')
        batch_op.drop_column('email')

    with op.batch_alter_table('super_admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_super_admin_username'), type_='unique')

    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('excellence_categories')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_review_booking_id'), type_='unique')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_owner_phone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_owner_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_owner_email'), type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('google_id')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_complaint',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
